[2024-07-24T06:27:52.553+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T06:27:52.566+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_postgres_dag.check_data manual__2024-07-24T06:27:50.341776+00:00 [queued]>
[2024-07-24T06:27:52.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_postgres_dag.check_data manual__2024-07-24T06:27:50.341776+00:00 [queued]>
[2024-07-24T06:27:52.570+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T06:27:52.577+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_data> on 2024-07-24 06:27:50.341776+00:00
[2024-07-24T06:27:52.580+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1442) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T06:27:52.580+0000] {standard_task_runner.py:64} INFO - Started process 1444 to run task
[2024-07-24T06:27:52.581+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 's3_to_postgres_dag', 'check_data', 'manual__2024-07-24T06:27:50.341776+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/accommodations.py', '--cfg-path', '/tmp/tmpbx4260ft']
[2024-07-24T06:27:52.582+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask check_data
[2024-07-24T06:27:52.621+0000] {task_command.py:426} INFO - Running <TaskInstance: s3_to_postgres_dag.check_data manual__2024-07-24T06:27:50.341776+00:00 [running]> on host 7f96a5b4d944
[2024-07-24T06:27:52.711+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_postgres_dag' AIRFLOW_CTX_TASK_ID='check_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T06:27:50.341776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T06:27:50.341776+00:00'
[2024-07-24T06:27:52.712+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T06:27:52.721+0000] {logging_mixin.py:188} INFO - Total records in your_table: 0
[2024-07-24T06:27:52.721+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-24T06:27:52.722+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T06:27:52.730+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=s3_to_postgres_dag, task_id=check_data, run_id=manual__2024-07-24T06:27:50.341776+00:00, execution_date=20240724T062750, start_date=20240724T062752, end_date=20240724T062752
[2024-07-24T06:27:52.753+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T06:27:52.778+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T06:27:52.780+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
